apiVersion: v1
kind: PersistentVolume
metadata:
  name: node2-mysql-pv-devtool
spec:
  storageClassName: managed-local-storage
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /home/local-storage/devtool-mysql
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node2
