apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-database-data-devtool-pvc
spec:
  storageClassName: managed-local-storage
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  volumeName: node2-mysql-pv-devtool
