apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-pvc
spec:
  storageClassName: managed-local-storage
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200Gi
  volumeName: samba-pv
